services:
  foodpal-backend:
    build:
      context: ./food-backend
    container_name: foodpal-backend
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      DATASOURCE_URL: jdbc:mysql://mysql:3306/foodpal?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
      DATASOURCE_USERNAME: foodpal
      DATASOURCE_PASSWORD: foodpal_2026
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: AxBzQbS4wjH9R51b
      MINIO_SECRET_KEY: NNJxorLf4p7Zd1rdJAurEXgP
      MINIO_BUCKET_NAME: foodpal-project
      JWT_SECRET: foodpal-jwt-secret-please-change-in-production-2026-very-long
      APP_PUBLIC_BASE_URL: http://107.148.176.142:9040
    ports:
      - "9040:9901"
    networks:
      - default
      - shared-infra

  foodpal-frontend:
    build:
      context: ./food-frontend
    container_name: foodpal-frontend
    restart: unless-stopped
    depends_on:
      - foodpal-backend
    ports:
      - "9041:80"

  foodpal-uniapp-h5:
    build:
      context: ./food-uniapp
      dockerfile: Dockerfile.h5
    container_name: foodpal-uniapp-h5
    restart: unless-stopped
    depends_on:
      - foodpal-backend
    ports:
      - "9042:8080"

networks:
  shared-infra:
    external: true
    name: shared-infra
